### ISSUE TITLE
Too much Output 

### ISSUE THREAD

**Issue by spyyes** [pietrobraione/jbse#24]
Hi,
I'm a new starter of jbse. When I run the _basic example_ -- IfExample, the output was extremely long (I attached the file in my appendix).
I tried to figure out that this due to too many variables and structures from the external libraries.
Could you please tell me whether there are configurations to filter them out?

[runIf_z3.txt](https://github.com/pietrobraione/jbse/files/2952270/runIf_z3.txt)

**Comment by pietrobraione** [comment]
Hi, I have changed some defaults, now the output is shorter. In general, if you set p.setStateFormatMode(StateFormatMode.FULLTEXT) instead of p.setStateFormatMode(StateFormatMode.TEXT) you will have a longer output. Same if you set p.setMakePreInitClassesSymbolic(true), that is not really a useful option if you do not use JBSE for generating test cases (I turned it on by default before I decided that it is better to leave it off by default).
